# dependabot configuration for TFC project

version: 2
updates:
  - directory: /scr/backend
    open-pull-requests-limit: 10
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: "daily"
      timezone: 05:00 UTC
  - directory: /scr/frontend
    open-pull-requests-limit: 10
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: "daily"
      timezone: 05:00 UTC
